### ISSUE TITLE
Enable upload and transform with cmd line tool of local files not in zip file

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#21]
The command line tool needs to be able to collect and send files directly from the local directory of the user. This will involve a svn/vlt style configuration and function whereby the local directory is paired with the remote AEM instance (and a particular path therein).

**Comment by jralonso84** [comment]
To reach this issue, we are thinking about changing command line instead of using curl command, creating a java main class to accomplish it. It will be able to pass the different params (src, transformer, target, master file and custom properties) and a path (a zip file or a local folder with all necessary files inside).

Let us know what you think about it.

**Comment by ppiegaze** [comment]
I agree. A java program is needed for this.

**Comment by jralonso84** [comment]
I've almost finished this issue adapting command line into a simple java class. I have to adapt script.bat and script.sh in the project as examples how to invoke this new feature and update README.md as well.
