### ISSUE TITLE
Remove Eclipse config files

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#31]
The eclipse specific config files in the git repo should be removed. Such files should remain local and not checked in. They should be covered within .gitignore.

**Comment by acollign** [comment]
I do agree with @ppiegaze. However sharing editor configuration is a good practice which prevents large diff just because the indentation or import automatic organization is not the same. Thus I would suggest we rely on editor config [1] to offer consistency and save time while merging.

[1] http://editorconfig.org/

**Comment by acollign** [comment]
Hi guys, I just pushed a simple editorconfig. Feel free to have a look at it and make any changes.
Next step will be to install the eclipse plugin [2] and then to perform a code clean up.

A dry run with IntelliJ touches:
- TransformerWorkflowProcess.java
- upload-content.jsp

[2] https://github.com/ncjones/editorconfig-eclipse

**Comment by jralonso84** [comment]
Eclipse config files have been removed

**Comment by acollign** [comment]
Thanks! Have you already installed the plugin? -- just curious.

**Comment by jralonso84** [comment]
Not yet ;). I'll install it soon.
