### ISSUE TITLE
Provide detailed error feedback when import fails

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#43]
It would help us a lot in testing (not just automated tetsting, but manual testing) if we could have immediate feedback in the importer tool page about why an import has failed (no such target path, missing config file etc etc.) 

Are such messages already being written to the error log? If not there should also be proper error logging with detailed messages too.

**Comment by galapagoss** [comment]
Ok for a detailed log in the importer service, I need to add a debug log, Instead for the error log everything is traced (missing data, not valid inputs, exceptions). In these cases the importer raise an exception which will be written in the error log by the launcher (workflow step).
Since the importer service is processed by a workflow my question is how I can give a prompt feedback in the tool page. Maybe I can add a new method in the interface (i.e. dataCheckOut()) which makes a basic validation of input data, but I think it could be meant like a mash up.
What do you think about?

**Comment by ppiegaze** [comment]
Ok, don't worry bout the tool page, a good debug and error log is what we really need

**Comment by galapagoss** [comment]
OK, I extended the log including the debug mode and I centralized the xml filter building as well (fixing a little bug)
Do you need a couple of integration test for checking some cases?

**Comment by ppiegaze** [comment]
Sure, the more tests the better :-)
